# Generated by Django 5.2.5 on 2025-08-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('passw', models.CharField(max_length=25)),
            ],
        ),
    ]
